/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract */
        post: operations["extract_api_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Geocode Address */
        post: operations["geocode_address_api_geocode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Case */
        post: operations["analyze_case_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advocate/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Columns
         * @description The file's own column names, so the user can map them before anything is parsed.
         *
         *     A separate call rather than a first pass of the analysis, because the mapping is a
         *     decision the user makes and the file has to be on screen before they can make it.
         */
        post: operations["columns_api_advocate_columns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advocate/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Batch */
        post: operations["analyze_batch_api_advocate_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advocate/analyze-affidavits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Affidavits
         * @description The same report, built from affidavits the defendant flow already confirmed.
         */
        post: operations["analyze_affidavits_api_advocate_analyze_affidavits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/advocate/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Csv
         * @description The report as a file, so it can be attached to something rather than screenshotted.
         *
         *     The client posts back the report it already holds rather than the server recomputing
         *     it: there is no case id because there is nothing stored, and re-uploading the whole
         *     spreadsheet to get a CSV of a result already on screen would be the wrong trade.
         */
        post: operations["export_csv_api_advocate_export_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvocateAnalysis */
        AdvocateAnalysis: {
            /** Reports */
            reports: components["schemas"]["ServerReport"][];
            /** Rejected */
            rejected: components["schemas"]["RejectedRow"][];
            /**
             * Records
             * @default []
             */
            records: components["schemas"]["ServiceRecord"][];
            mapping: components["schemas"]["AdvocateColumnMapping"];
            stats: components["schemas"]["AdvocateStats"];
        };
        /**
         * AdvocateColumnMapping
         * @description Which column of the uploaded file holds each field. Values are header names.
         *
         *     Two things are required and each may be given two ways, because case-management
         *     systems export both: a time is either one column or a date column plus a time column,
         *     and a place is either a coordinate pair or an address to look up.
         */
        AdvocateColumnMapping: {
            /** Server Id */
            server_id: string;
            /** At */
            at?: string | null;
            /** Date */
            date?: string | null;
            /** Time */
            time?: string | null;
            /** Lat */
            lat?: string | null;
            /** Lng */
            lng?: string | null;
            /** Address */
            address?: string | null;
            /** Case Ref */
            case_ref?: string | null;
            /** Outcome */
            outcome?: string | null;
            /** Recipient Desc */
            recipient_desc?: string | null;
        };
        /** AdvocateStats */
        AdvocateStats: {
            /** Rows Read */
            rows_read: number;
            /** Records */
            records: number;
            /** Rejected */
            rejected: number;
            /** Servers */
            servers: number;
            /** Addresses Geocoded */
            addresses_geocoded: number;
            /** Records Returned */
            records_returned: number;
            /** Params Version */
            params_version: string;
            /** Engine Version */
            engine_version: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** Affidavit */
        Affidavit: {
            /** Index Number */
            index_number?: string | null;
            /** Court */
            court?: string | null;
            /** Plaintiff */
            plaintiff?: string | null;
            /** Defendant Name */
            defendant_name: string;
            /** Server Name */
            server_name?: string | null;
            /** Server License */
            server_license?: string | null;
            /** Agency License */
            agency_license?: string | null;
            method: components["schemas"]["ServiceMethod"];
            /**
             * Served At
             * Format: date-time
             */
            served_at: string;
            /** Served Address */
            served_address: string;
            served_location?: components["schemas"]["LatLng"] | null;
            /** Recipient Name */
            recipient_name?: string | null;
            /** Recipient Relationship */
            recipient_relationship?: string | null;
            recipient_description?: components["schemas"]["PersonDescription"] | null;
            /**
             * Attempts
             * @default []
             */
            attempts: components["schemas"]["ServiceAttempt"][];
            /** Mailing Date */
            mailing_date?: string | null;
            /** Mailing Address */
            mailing_address?: string | null;
            /** Proof Filed Date */
            proof_filed_date?: string | null;
            /** Source Sha256 */
            source_sha256: string;
            /**
             * Field Confidence
             * @default {}
             */
            field_confidence: {
                [key: string]: number;
            };
            /**
             * User Confirmed
             * @default false
             */
            user_confirmed: boolean;
        };
        /**
         * AffidavitDraft
         * @description What came off the document. Nothing here is trusted until the user confirms it.
         *
         *     Dates, times and `method` stay as free text on purpose. A model that writes
         *     "June 12, 2025" has to produce a note the user can act on, not a validation failure
         *     that throws the whole extraction away.
         */
        AffidavitDraft: {
            /** Index Number */
            index_number?: string | null;
            /** Court */
            court?: string | null;
            /** Plaintiff */
            plaintiff?: string | null;
            /** Defendant Name */
            defendant_name?: string | null;
            /** Server Name */
            server_name?: string | null;
            /** Server License */
            server_license?: string | null;
            /** Agency License */
            agency_license?: string | null;
            /** Method */
            method?: string | null;
            /** Served Date */
            served_date?: string | null;
            /** Served Time */
            served_time?: string | null;
            /** Served At */
            served_at?: string | null;
            /**
             * Served At Ambiguous
             * @default false
             */
            served_at_ambiguous: boolean;
            /** Served Address */
            served_address?: string | null;
            served_location?: components["schemas"]["LatLng"] | null;
            /** Recipient Name */
            recipient_name?: string | null;
            /** Recipient Relationship */
            recipient_relationship?: string | null;
            recipient_description?: components["schemas"]["PersonDescription"] | null;
            /**
             * Attempts
             * @default []
             */
            attempts: components["schemas"]["AttemptDraft"][];
            /** Mailing Date */
            mailing_date?: string | null;
            /** Mailing Address */
            mailing_address?: string | null;
            /** Proof Filed Date */
            proof_filed_date?: string | null;
            /**
             * Field Confidence
             * @default {}
             */
            field_confidence: {
                [key: string]: number;
            };
            /**
             * Evidence Quotes
             * @default {}
             */
            evidence_quotes: {
                [key: string]: string;
            };
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            affidavit: components["schemas"]["Affidavit"];
            /** Fixes */
            fixes: components["schemas"]["LocationFix"][];
            /**
             * Household
             * @default []
             */
            household: components["schemas"]["HouseholdMember"][];
            /** Knowledge Date */
            knowledge_date?: string | null;
            /** Judgment Entry Date */
            judgment_entry_date?: string | null;
        };
        /**
         * AttemptDraft
         * @description A prior service attempt as extracted, before normalisation.
         */
        AttemptDraft: {
            /** At Date */
            at_date?: string | null;
            /** At Time */
            at_time?: string | null;
            /** At */
            at?: string | null;
            /** Address */
            address?: string | null;
            location?: components["schemas"]["LatLng"] | null;
            /** Outcome */
            outcome?: string | null;
        };
        /** Body_analyze_batch_api_advocate_analyze_post */
        Body_analyze_batch_api_advocate_analyze_post: {
            /** File */
            file: string;
            /** Mapping */
            mapping: string;
        };
        /** Body_columns_api_advocate_columns_post */
        Body_columns_api_advocate_columns_post: {
            /** File */
            file: string;
        };
        /** Body_extract_api_extract_post */
        Body_extract_api_extract_post: {
            /** File */
            file: string;
        };
        /** CaseAnalysis */
        CaseAnalysis: {
            affidavit: components["schemas"]["Affidavit"];
            /** Verdicts */
            verdicts: components["schemas"]["ClaimVerdict"][];
            /** Findings */
            findings: components["schemas"]["Finding"][];
            overall: components["schemas"]["ClaimTier"];
            deadlines: components["schemas"]["Deadlines"];
            /** Params Version */
            params_version: string;
            /** Engine Version */
            engine_version: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * ClaimTier
         * @enum {string}
         */
        ClaimTier: "contradicted" | "consistent" | "no_data" | "inconclusive";
        /** ClaimVerdict */
        ClaimVerdict: {
            /** Claim Ref */
            claim_ref: string;
            /**
             * Claimed At
             * Format: date-time
             */
            claimed_at: string;
            claimed_location: components["schemas"]["LatLng"];
            tier: components["schemas"]["ClaimTier"];
            /** Nearest Fix Km */
            nearest_fix_km?: number | null;
            /** Required Speed Kmh */
            required_speed_kmh?: number | null;
            /**
             * Fixes Used
             * @default []
             */
            fixes_used: components["schemas"]["LocationFix"][];
        };
        /** Deadlines */
        Deadlines: {
            /** Knowledge Date */
            knowledge_date?: string | null;
            /** Judgment Entry Date */
            judgment_entry_date?: string | null;
            /** Cplr 317 Deadline */
            cplr_317_deadline?: string | null;
            /** Cplr 317 Outer Limit */
            cplr_317_outer_limit?: string | null;
            /** Note */
            note: string;
        };
        /**
         * ExtractionResult
         * @description The response of `POST /api/extract`.
         */
        ExtractionResult: {
            draft: components["schemas"]["AffidavitDraft"];
            /**
             * Notes
             * @default []
             */
            notes: components["schemas"]["ValidationNote"][];
            /** Provider */
            provider: string;
            /** Source Sha256 */
            source_sha256: string;
            /** N Pages */
            n_pages: number;
            /** Has Text Layer */
            has_text_layer: boolean;
            /** Used Vision */
            used_vision: boolean;
        };
        /** Finding */
        Finding: {
            /** Code */
            code: string;
            severity: components["schemas"]["Severity"];
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /**
             * Numbers
             * @default {}
             */
            numbers: {
                [key: string]: number | string;
            };
            /** Legal Ref */
            legal_ref?: string | null;
        };
        /**
         * FixKind
         * @enum {string}
         */
        FixKind: "visit" | "path" | "transaction" | "manual";
        /** GeocodeRequest */
        GeocodeRequest: {
            /** Address */
            address: string;
        };
        /**
         * GeocodeResponse
         * @description `result` is null when the address could not be resolved inside New York City.
         */
        GeocodeResponse: {
            result?: components["schemas"]["GeocodeResult"] | null;
        };
        /**
         * GeocodeResult
         * @description A resolved NYC address. `label` is GeoSearch's normalised form of the input.
         */
        GeocodeResult: {
            location: components["schemas"]["LatLng"];
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            /**
             * Source
             * @enum {string}
             */
            source: "geosearch" | "cache";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Engine Version */
            engine_version: string;
            /** Params Version */
            params_version: string;
            /** Llm Provider */
            llm_provider: string;
        };
        /** HouseholdMember */
        HouseholdMember: {
            /** Label */
            label: string;
            /** Sex */
            sex?: ("male" | "female" | "other") | null;
            /** Age */
            age?: number | null;
            /** Height In */
            height_in?: number | null;
            /**
             * Is Defendant
             * @default false
             */
            is_defendant: boolean;
        };
        /** ImpossiblePair */
        ImpossiblePair: {
            a: components["schemas"]["ServiceRecord"];
            b: components["schemas"]["ServiceRecord"];
            /** Distance Km */
            distance_km: number;
            /** Minutes */
            minutes: number;
            /** Required Speed Kmh */
            required_speed_kmh: number;
        };
        /** LatLng */
        LatLng: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** LocationFix */
        LocationFix: {
            /**
             * T
             * Format: date-time
             */
            t: string;
            /** T End */
            t_end?: string | null;
            loc: components["schemas"]["LatLng"];
            /** Accuracy M */
            accuracy_m?: number | null;
            kind: components["schemas"]["FixKind"];
            /** Source */
            source: string;
            /** Label */
            label?: string | null;
        };
        /** PersonDescription */
        PersonDescription: {
            /** Sex */
            sex?: ("male" | "female" | "unknown") | null;
            /** Age Min */
            age_min?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Height In Min */
            height_in_min?: number | null;
            /** Height In Max */
            height_in_max?: number | null;
            /** Weight Lb Min */
            weight_lb_min?: number | null;
            /** Weight Lb Max */
            weight_lb_max?: number | null;
            /** Hair */
            hair?: string | null;
            /** Raw Text */
            raw_text?: string | null;
        };
        /**
         * RejectedRow
         * @description A row that could not be turned into a service record, and why.
         *
         *     Rejections are part of the answer, not an error path. An advocate is assembling a
         *     complaint, and a parser that silently drops the eleven rows it could not read hands
         *     them a report whose denominator is wrong.
         */
        RejectedRow: {
            /** Row */
            row: number;
            /** Code */
            code: string;
            /** Reason */
            reason: string;
        };
        /** ServerReport */
        ServerReport: {
            /** Server Id */
            server_id: string;
            /** N Records */
            n_records: number;
            /** Impossible Pairs */
            impossible_pairs: components["schemas"]["ImpossiblePair"][];
            /** Max Services Per Hour */
            max_services_per_hour: number;
            /** Repeated Descriptions */
            repeated_descriptions: [
                string,
                number
            ][];
            /** Risk Rank */
            risk_rank: number;
        };
        /** ServiceAttempt */
        ServiceAttempt: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Address */
            address: string;
            location?: components["schemas"]["LatLng"] | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "served" | "affixed" | "not_home" | "refused" | "other";
        };
        /**
         * ServiceMethod
         * @enum {string}
         */
        ServiceMethod: "308_1" | "308_2" | "308_4" | "unknown";
        /** ServiceRecord */
        ServiceRecord: {
            /** Server Id */
            server_id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            loc: components["schemas"]["LatLng"];
            /** Address */
            address?: string | null;
            /** Case Ref */
            case_ref?: string | null;
            /** Outcome */
            outcome?: string | null;
            /** Recipient Desc */
            recipient_desc?: string | null;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "strong" | "moderate" | "info";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationNote
         * @description One deterministic observation about a draft field, shown next to that field.
         */
        ValidationNote: {
            /** Field */
            field: string;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    extract_api_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_api_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geocode_address_api_geocode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeocodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_case_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    columns_api_advocate_columns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_columns_api_advocate_columns_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_batch_api_advocate_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_batch_api_advocate_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvocateAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_affidavits_api_advocate_analyze_affidavits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Affidavit"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvocateAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_api_advocate_export_csv_post: {
        parameters: {
            query?: {
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerReport"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
