/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract */
        post: operations["extract_api_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Geocode Address */
        post: operations["geocode_address_api_geocode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AffidavitDraft
         * @description What came off the document. Nothing here is trusted until the user confirms it.
         *
         *     Dates, times and `method` stay as free text on purpose. A model that writes
         *     "June 12, 2025" has to produce a note the user can act on, not a validation failure
         *     that throws the whole extraction away.
         */
        AffidavitDraft: {
            /** Index Number */
            index_number?: string | null;
            /** Court */
            court?: string | null;
            /** Plaintiff */
            plaintiff?: string | null;
            /** Defendant Name */
            defendant_name?: string | null;
            /** Server Name */
            server_name?: string | null;
            /** Server License */
            server_license?: string | null;
            /** Agency License */
            agency_license?: string | null;
            /** Method */
            method?: string | null;
            /** Served Date */
            served_date?: string | null;
            /** Served Time */
            served_time?: string | null;
            /** Served At */
            served_at?: string | null;
            /**
             * Served At Ambiguous
             * @default false
             */
            served_at_ambiguous: boolean;
            /** Served Address */
            served_address?: string | null;
            served_location?: components["schemas"]["LatLng"] | null;
            /** Recipient Name */
            recipient_name?: string | null;
            /** Recipient Relationship */
            recipient_relationship?: string | null;
            recipient_description?: components["schemas"]["PersonDescription"] | null;
            /**
             * Attempts
             * @default []
             */
            attempts: components["schemas"]["AttemptDraft"][];
            /** Mailing Date */
            mailing_date?: string | null;
            /** Mailing Address */
            mailing_address?: string | null;
            /** Proof Filed Date */
            proof_filed_date?: string | null;
            /**
             * Field Confidence
             * @default {}
             */
            field_confidence: {
                [key: string]: number;
            };
            /**
             * Evidence Quotes
             * @default {}
             */
            evidence_quotes: {
                [key: string]: string;
            };
        };
        /**
         * AttemptDraft
         * @description A prior service attempt as extracted, before normalisation.
         */
        AttemptDraft: {
            /** At Date */
            at_date?: string | null;
            /** At Time */
            at_time?: string | null;
            /** At */
            at?: string | null;
            /** Address */
            address?: string | null;
            location?: components["schemas"]["LatLng"] | null;
            /** Outcome */
            outcome?: string | null;
        };
        /** Body_extract_api_extract_post */
        Body_extract_api_extract_post: {
            /** File */
            file: string;
        };
        /**
         * ExtractionResult
         * @description The response of `POST /api/extract`.
         */
        ExtractionResult: {
            draft: components["schemas"]["AffidavitDraft"];
            /**
             * Notes
             * @default []
             */
            notes: components["schemas"]["ValidationNote"][];
            /** Provider */
            provider: string;
            /** Source Sha256 */
            source_sha256: string;
            /** N Pages */
            n_pages: number;
            /** Has Text Layer */
            has_text_layer: boolean;
            /** Used Vision */
            used_vision: boolean;
        };
        /** GeocodeRequest */
        GeocodeRequest: {
            /** Address */
            address: string;
        };
        /**
         * GeocodeResponse
         * @description `result` is null when the address could not be resolved inside New York City.
         */
        GeocodeResponse: {
            result?: components["schemas"]["GeocodeResult"] | null;
        };
        /**
         * GeocodeResult
         * @description A resolved NYC address. `label` is GeoSearch's normalised form of the input.
         */
        GeocodeResult: {
            location: components["schemas"]["LatLng"];
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            /**
             * Source
             * @enum {string}
             */
            source: "geosearch" | "cache";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Engine Version */
            engine_version: string;
            /** Params Version */
            params_version: string;
            /** Llm Provider */
            llm_provider: string;
        };
        /** LatLng */
        LatLng: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** PersonDescription */
        PersonDescription: {
            /** Sex */
            sex?: ("male" | "female" | "unknown") | null;
            /** Age Min */
            age_min?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Height In Min */
            height_in_min?: number | null;
            /** Height In Max */
            height_in_max?: number | null;
            /** Weight Lb Min */
            weight_lb_min?: number | null;
            /** Weight Lb Max */
            weight_lb_max?: number | null;
            /** Hair */
            hair?: string | null;
            /** Raw Text */
            raw_text?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationNote
         * @description One deterministic observation about a draft field, shown next to that field.
         */
        ValidationNote: {
            /** Field */
            field: string;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    extract_api_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_api_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geocode_address_api_geocode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeocodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
